WIP: Refactor for scraped
everypolitician-scrapers/albania-kuvendi pull request #2
Opened 2017-01-24 16:58 UTC by ondenman

The scraper is currently broken and will need to be reworked. This is a step towards that.

2017-01-25 15:04 UTC, tmtmtmtm requested changes
Although I've left lots of comments on the implementation of `headings`, I'm not convinced that this is even really the right approach here at all. This seems like a very complex set-up for a series of "foo: bar" pairs.

I haven't looked closely enough at the source data, particularly to see if it varies, so I'm not sure what the cleanest approach would be. Does a variation of `table.xpath('.//span[contains(., "Vendlindja")]')`, (etc) not work?

This all seems complex enough that I think you should add tests for each field on at least one member (more if the layout actually does vary)

2017-01-25 15:04 UTC, tmtmtmtm commented on lib/member_page.rb
> +    noko.enum_for(:traverse).select { |node| node.name == 'h1' }
I'm having difficulty following what this is meant to be doing. How does this differ from `noko.css('h1')`?

2017-01-25 15:04 UTC, tmtmtmtm commented on lib/member_page.rb
> +  def headings
The name of this method doesn't really convey what it actually _is_. I certainly wouldn't expect a `headings` method to return a series of Regexps!

2017-01-25 15:04 UTC, tmtmtmtm commented on lib/member_page.rb
> +        .map { |h| /(#{h})/ }
I think it would be clearer to use `Regexp.new` here.

2017-01-25 15:04 UTC, tmtmtmtm commented on scraper.rb
> +                                               .merge((scrape member.source => MemberPage).to_h))
The argument to `save_sqlite` is a bit too complex here. Building it up into a variable first is both cleaner, and also lets us print it out or examine it in `pry`, when debugging.

2017-01-25 15:04 UTC, tmtmtmtm commented on scraper.rb
> +  unless (next_page = noko_for(url).css('a.next/@href')).empty?
One of the goals of porting to `scraped` is getting rid of the `noko_for` method. You shouldn't be fetching or playing with the HTML directly in `scraper.rb` — everything you need access to should be in the `Scraped::HTML` subclasses.

2017-02-07 16:58 UTC, tmtmtmtm requested changes
It's a little bit difficult to see why each person here is being chosen to test. I'd suggest switching these tests to be data driven (i.e. testing the result of `.to_h` against what you expect that to give for each person), and introducing each with a something that explains _why_ you're picking them (e.g "test person with foo and no bar", "test person with bar and no foo")

2017-02-07 16:58 UTC, tmtmtmtm commented on test/member_test.rb
> +  it 'should have not have data for birt_place' do
you say you're testing 'birth_place' (and misspelling it…), but the test is actually for `birth_date`

2017-02-07 16:58 UTC, tmtmtmtm commented on test/test_helper.rb
> +require 'minitest/around/spec'
you'll also want to require 'pry' here, so that it's always available when interacting with tests.

2017-02-07 16:58 UTC, tmtmtmtm commented on lib/member_page.rb
> +      line_for('Datëlindja').match(/(\d\d\.\d\d\.\d\d\d\d)/) { Regexp.last_match(1) }.to_s.tidy
This part can be simplified to `line_for('Datëlindja')[/(\d\d\.\d\d\.\d\d\d\d)/, 1]`

2017-02-09 08:17 UTC, tmtmtmtm requested changes

2017-02-09 08:17 UTC, tmtmtmtm commented on lib/member_page.rb
> +         .last
This combination of `split(':').drop(1).last` is quite confusing. I _think_ what it's doing can be expressed slightly better as `split(':', 2)[1]`, but it's not clear whether you're expecting fields with more than one ':' or not. (If you are, you need to add a test case for them!)

2017-02-09 08:17 UTC, tmtmtmtm commented on lib/member_page.rb
> +         .tidy
`.chomp('.').tidy` is in a slightly unexpected order, as it only removes the '.' if it's exactly the last character (i.e. it doesn't if the string ends in '. ') 

Is that deliberate behaviour?

2017-02-09 08:17 UTC, tmtmtmtm commented on test/member_test.rb
> +  end
There's a lot of duplication in each test.

I'd suggest hoisting out the setup:

```ruby
  around { |test| VCR.use_cassette(cassette, &test) }
  subject { MemberPage.new(response: Scraped::Request.new(url: url).response) }
```

and then within each `describe` block, setting the data you need:

```
  describe 'Member page without area data' do
    let(:cassette) { 'DukaAgron' }
    let(:url) { 'https://www.parlament.al/deputet/agron-duka-2/' }
    …
```

2017-02-09 08:21 UTC, tmtmtmtm commented on test/member_test.rb
> +  end
or, better still, you shouldn't even need to name the cassette — just derive it from the URL:

```ruby
  around { |test| VCR.use_cassette(url.split('/').last, &test) }
```

2017-02-09 17:12 UTC, ondenman commented on lib/member_page.rb
> +         .last
This is to handle cases where the record heading is present (for example 'Vendlindja:') but isn't followed by the actual record. This is being tested in: 13fc0eb0cfeb6e1d1647b3f1f3e25191354c4817

I've replaced `split(':').drop(1).last` with your example.

2017-02-09 17:28 UTC, ondenman commented on lib/member_page.rb
> +         .tidy
No. An oversight. I've reversed their order.

2017-02-16 14:54 UTC, tmtmtmtm requested changes
I've pulled the test-framework out to `master`, and fixed master to actually run to completion so we can compare the output. (I've also rebased this over that)

Unfortunately this loses quite a lot of data. If you add a test for anastas-angjeli you should be able to see what's going wrong.

2017-02-21 16:19 UTC, ondenman commented
@tmtmtm Master is not running to completion for me. It still enters pry when scraping `https://www.parlament.al/deputet/genc-ruli/`.

2017-02-23 09:44 UTC, tmtmtmtm commented
@ondenman I've pushed another commit that bails out in that case.

2017-05-17 11:53 UTC, ondenman commented
Closing in favour https://github.com/everypolitician-scrapers/albania-kuvendi/pull/8

2017-05-17 11:53 UTC, closed without merging